### ISSUE TITLE
Bug Report: Blank Window

### ISSUE THREAD

**Issue by MissStrong** [Deprecator16/Maze-Game-CS#1]
I downloaded the project from the Back-End branch (most recent commit is 0095c12), and all I got was a blank window with the title "A Random Maze Game" when I ran the program. No exceptions appear to be thrown, although "Note: Some input files use unchecked or unsafe operations." is printed to the console.
![](https://user-images.githubusercontent.com/44328647/51606185-352a0f80-1edf-11e9-8461-b7acf639ea60.png)

**Comment by Deprecator16** [comment]
I've attempted to confirm this on 4 separate Windows computers. This be an issue of OS or perhaps a randomness with the way painting is done in JFrames?

**Comment by MissStrong** [comment]
I tried again (most recent commit is f9e9011). Now this is what shows up.
![](https://user-images.githubusercontent.com/44328647/51677493-d2e91180-1fa7-11e9-94f6-aadb1443b050.png)

I'm on a Mac, so that might be why. I'll try it later on a school desktop computer.

**Comment by Deprecator16** [comment]
That is the correct output, though, if user control (WASD/Arrow keys) does not work, then there might still be an issue.

**Comment by MissStrong** [comment]
Do the user controls work on your machine? I tried on both my personal laptop (OS Mojave v. 10.14.2) and a school desktop (Windows 10 Pro), but nothing happens when I press WASD or the arrow keys.

My guess is that you may be missing a `this.requestFocus();`, which may be needed for the key listeners to work.

**Comment by Deprecator16** [comment]
I just implemented the `requestFocus();` in the `GraphicalDisplay` class constructor and it seems to work on my machine. User controls work immediately without having to click the window.
